language: scala
sudo: false
matrix:
  include:
    - scala: 2.10.6
      script: ./sbt ++$TRAVIS_SCALA_VERSION clean test mimaReportBinaryIssues

    - scala: 2.11.8
      script: ./sbt ++$TRAVIS_SCALA_VERSION clean test mimaReportBinaryIssues
